### ISSUE TITLE
[How To Fix] Warning : correct props name: "partialVisible" as old typo will be removed in future versions! 

### ISSUE THREAD

**Issue by ericklarsen** [YIZHUANG/react-multi-carousel#214]
Hi guys, i get some warning like this when I use partialVisible props.
**How to fix it?**

![image](https://user-images.githubusercontent.com/32609329/100578249-70d06480-3314-11eb-8853-f2342919a873.png)

And i was trying to look at the **_types.d.ts_** file from react-multi-carousel and I found this.
![image](https://user-images.githubusercontent.com/32609329/100578337-a8d7a780-3314-11eb-96c8-f142a670ccfa.png)

Why are there 2 parameters with the name **_PartialVisible_**? And one of them looks like a typo

**Expected behavior**
The warning is gone

**Comment by abhinavdalal** [comment]
@ericklarsen i added the second param as the original code had a typo.. i wanted to clean the typo but keep backwards compatibility..  if your getting the warning its because as the warning says your using the old typo prop which will be removed in the next major version update.. just change to using the one without the typo to remove the warnings :)

removing the typo prop is easy but i am sure it will lead to may users facing errors or incorrect functionality.. we want to clean up the typo but at the same time do it in a versioned manner to maintain compatibility.. fixing a typo does not justify a major version release.. hope you understand :)

**Comment by abhinavdalal** [comment]
i am confused.. you should not be getting warning for `partialVisible`; this is a mistake..

it should only show for `partialVisble`

I will need to investigate this!

**Comment by abhinavdalal** [comment]
https://github.com/YIZHUANG/react-multi-carousel/blob/8786995beea8ec3e04dd026d5bc38b41c78b8eab/src/CarouselItems.tsx#L43

@ericklarsen although the warning says `partialVisible` needs to be corrected..  the if condition is correct it is on the typo param that will be deprecated in the future.. so you need to pass correct the param passed.. ~~partialVisble~~ `partialVisible`

**Comment by abhinavdalal** [comment]
@ericklarsen @YIZHUANG this issue can be closed!

**Comment by ericklarsen** [comment]
Hi abhinav, thanks for response my issue,
Btw i use the correct param "partialVisible" not "partialVisble",
and right now the warning is gone, i don't know why, but it's not showing again, LOL, it's like a magic hahaha

**Comment by ericklarsen** [comment]
![image](https://user-images.githubusercontent.com/32609329/100583194-f1935e80-331c-11eb-9b5b-eeb620eeba18.png)
Btw abhinav, I'm using the correct param. Why the warning still exist?

**Comment by ericklarsen** [comment]
Thank guys!
