### ISSUE TITLE
Seems not to work on Next.js

### ISSUE THREAD

**Issue by simplenotezy** [YIZHUANG/react-multi-carousel#249]
**Describe the bug**
Slider renders empty on page. It contains children, but when inspecting DOM, no HTML elements are generated.

**To Reproduce**
I tried following the minimal example here: https://github.com/YIZHUANG/react-multi-carousel#minimum-working-set-up

In a Next.js project.

**Expected behavior**
Slider should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/3786627/117064325-53218400-ad26-11eb-997c-ffd1ad3f432f.png)
![image](https://user-images.githubusercontent.com/3786627/117064470-88c66d00-ad26-11eb-8554-19096adca13d.png)

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Chrome
 - Version Latest

**Comment by ascandella** [comment]
Possibly related to https://github.com/YIZHUANG/react-multi-carousel/issues/248

**Comment by YIZHUANG** [comment]
Can you provide a reproduction?

**Comment by simplenotezy** [comment]
Sorry, I've switched to Embla-Carousel.com. I think you could get a lot of inspiration in terms of how it's setup, and how clean and simple it is.

**Comment by simplenotezy** [comment]
Also, to support SSR frameworks like Gatsby and Next.js, simply check for "window" prior to initialising - that seems to be what Embla carousel does.

**Comment by alexcanessa** [comment]
@YIZHUANG this shouldn't be closed I don't think. Both Gatsby and Next have the same problem.

**Comment by ascandella** [comment]
I figured out the issue I was running into with Next.js.

Simply passing `ssr` is not enough, you also need to pass `deviceType` (and `responsive`, but I was already passing that). Otherwise, `shouldRenderOnSSR` here is false:  https://github.com/YIZHUANG/react-multi-carousel/blob/9f55f058cb4302a3700ebd81f5619f6ad182f030/src/utils/common.ts#L32-L34

If you look at the SSR example, this is done using `MobileDetect`: https://github.com/YIZHUANG/react-multi-carousel/blob/2b67aaaebbc31c91e51a15372b34014a1a506199/examples/ssr/pages/index.js#L17-L34

https://github.com/YIZHUANG/react-multi-carousel/blob/2b67aaaebbc31c91e51a15372b34014a1a506199/examples/ssr/pages/index.js#L112
