### ISSUE TITLE
Paritial -> Partial

### ISSUE THREAD

**Issue by robbie-c** [YIZHUANG/react-multi-carousel#54]
**Describe the bug**
In the documentation and in the code, there is a typo in the world partial and partially.

This appears in the type `responsiveType` and in the documentation around it.

**Comment by YIZHUANG** [comment]
Hi, thank you for catching this issue. This is fixed in https://github.com/YIZHUANG/react-multi-carousel/commit/e69474f556d86a3de4e4d0b2b8e36494c567356b.

paritialVisibilityGutter will continue to work for backward compatibility but with a warning to suggest to use partialVisibilityGutter instead and will be removed in the future.
